### ISSUE TITLE
Duplicit API call to Graphite API

### ISSUE THREAD

**Issue by zdenekpizl** [obfuscurity/nagios-scripts#20]
Calls of Graphite REST API from https://github.com/obfuscurity/nagios-scripts/blob/master/check_graphite#L95 and 
https://github.com/obfuscurity/nagios-scripts/blob/master/check_graphite#L99  are redundant and double the load.

Proposed way:
```ruby
  response = JSON.parse(RestClient.get(URI.encode(url)))
  if response.empty?
    puts "UNKNOWN no data reported by Graphite"
    exit EXIT_UNKNOWN
  else
    response.each do |cache| 
```

**Comment by obfuscurity** [comment]
Thanks!
