### ISSUE TITLE
500 Internal error on Graphite API

### ISSUE THREAD

**Issue by zdenekpizl** [obfuscurity/nagios-scripts#22]
Greetings!

I've noticed option "-z", "--zero-on-error", "Return 0 on a graphite 500 error". I am curious why are these internal errors managed explicitly. Is it something check_graphite invokes on API backend or is it just a workaround for known API behaviour?

I am observing "500 Internal errors" on my Graphite installation + check_graphite unpleasantly often. What could be the reason?

Thank you, with regards .zp.

**Comment by obfuscurity** [comment]
No idea why you're seeing 500 errors with your Graphite. There are a multitude of reasons that could happen, you should check your logs. The `-z` option was added in https://github.com/obfuscurity/nagios-scripts/pull/9 for the reasons described there.
