### ISSUE TITLE
I'd like a binary (ELF x86_64) for Linux

### ISSUE THREAD

**Issue by mwtzzz-zz** [obfuscurity/nagios-scripts#24]
I'd like to distribute check_graphite to our hosts, but most of our hosts cannot run it due to various ruby incompatility and package issues. Would it be possible for you to produce a portable version that we can run on amzn_linux and centos boxes?

**Comment by obfuscurity** [comment]
Sorry, this isn't something I have any interest in developing or maintaining. A quick Google led me to http://phusion.github.io/traveling-ruby/, perhaps this will work for you?

**Comment by mwtzzz-zz** [comment]
Thanks for the link, I'll check it out.
